/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BarChart: typeof import('./src/components/dashboard/BarChart.vue')['default']
    BarChartTowColumns: typeof import('./src/components/dashboard/BarChartTowColumns.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChangePasswordDialog: typeof import('./src/components/User/ChangePasswordDialog.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DoughnutChart: typeof import('./src/components/dashboard/DoughnutChart.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LineChart: typeof import('./src/components/dashboard/LineChart.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    PatientDetails: typeof import('./src/components/Patiesnt/patientDetails.vue')['default']
    PatientDialog: typeof import('./src/components/Patiesnt/PatientDialog.vue')['default']
    PatientProfileHeader: typeof import('./src/components/Patiesnt/PatientProfileHeader.vue')['default']
    PaymentDialog: typeof import('./src/components/Payments/PaymentDialog.vue')['default']
    PieChart: typeof import('./src/components/dashboard/PieChart.vue')['default']
    PolarChart: typeof import('./src/components/dashboard/PolarChart.vue')['default']
    RadarChart: typeof import('./src/components/dashboard/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatusWidget: typeof import('./src/components/dashboard/StatusWidget.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TreatmentHistory: typeof import('./src/components/Patiesnt/TreatmentHistory.vue')['default']
    UserDialog: typeof import('./src/components/User/UserDialog.vue')['default']
    UserProfileMenu: typeof import('./src/components/User/UserProfileMenu.vue')['default']
    VisitDialog: typeof import('./src/components/Patiesnt/VisitDialog.vue')['default']
    XRayDialog: typeof import('./src/components/Patiesnt/XRayDialog.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
