services:
  api:
    build:
      context: .
      dockerfile: src/NabdCare.Api/Dockerfile
    ports:
      - "5175:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=nabdcare_db;Username=postgres;Password=admin@123
      Jwt__Key: "${JWT_SECRET}"
      Jwt__Issuer: "NabdCareIssuer"
      Jwt__Audience: "NabdCareAudience"
      Jwt__ExpireMinutes: "60"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nabdcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: