
services:
  api:
    build:
      context: .
      dockerfile: src/NabdCare.Api/Dockerfile
    ports:
      - "5175:5175"
      - "7053:7053"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=nabdcare_db;Username=postgres;Password=admin@123
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nabdcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: