using Microsoft.AspNetCore.Mvc;
using NabdCare.Api.Extensions;
using NabdCare.Application.Common;
using NabdCare.Application.Common.Constants;
using NabdCare.Application.DTOs.Invoices;
using NabdCare.Application.Interfaces.Invoices;
using NabdCare.Domain.Entities.Invoices;

namespace NabdCare.Api.Endpoints;

public static class InvoiceEndpoints
{
    public static void MapInvoiceEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("invoices")
            .WithTags("Invoices");

        // ============================================
        // GET INVOICES (Paged + ABAC)
        // ============================================
        group.MapGet("/", async (
                [AsParameters] InvoiceListRequestDto request,
                [FromServices] IInvoiceService service,
                [FromServices] ITenantContext tenantContext) =>
            {
                // Force clinic filter for non-SuperAdmins (Defense in Depth)
                if (!tenantContext.IsSuperAdmin)
                {
                    request.ClinicId = tenantContext.ClinicId;
                }

                var result = await service.GetPagedAsync(request);
                return Results.Ok(result);
            })
            .RequireAuthorization()
            .RequirePermission(Permissions.Invoices.View)
            .WithAbac<Invoice>(
                Permissions.Invoices.View,
                "list",
                async ctx =>
                {
                    var tenant = ctx.RequestServices.GetRequiredService<ITenantContext>();
                    // Create a dummy context for the policy to evaluate "List" access
                    return await Task.FromResult(tenant.IsSuperAdmin
                        ? null
                        : new Invoice { ClinicId = tenant.ClinicId ?? Guid.Empty });
                })
            .WithName("GetInvoices")
            .WithSummary("Get Billing History")
            .Produces<Application.DTOs.Pagination.PaginatedResult<InvoiceDto>>()
            .Produces(StatusCodes.Status403Forbidden);

        // ============================================
        // GET INVOICE BY ID
        // ============================================
        group.MapGet("/{id:guid}", async (Guid id, [FromServices] IInvoiceService service) =>
            {
                var invoice = await service.GetByIdAsync(id);
                return invoice != null ? Results.Ok(invoice) : Results.NotFound();
            })
            .RequireAuthorization()
            .RequirePermission(Permissions.Invoices.View)
            // Note: ABAC check for specific ID is handled inside Service.GetByIdAsync
            // because we need to fetch the data to check ownership.
            .WithName("GetInvoiceById")
            .Produces<InvoiceDto>()
            .Produces(StatusCodes.Status404NotFound)
            .Produces(StatusCodes.Status403Forbidden);
        
        // NOTE: No POST/PUT here because invoices are generated by System logic
        // via SubscriptionService.
    }
}